"""empty message

Revision ID: 2ce8ab035ef6
Revises: 
Create Date: 2016-12-04 01:02:25.854680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce8ab035ef6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('startFrame', sa.Integer(), nullable=True),
    sa.Column('endFrame', sa.Integer(), nullable=True),
    sa.Column('chunks', sa.Integer(), nullable=True),
    sa.Column('filePath', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startFrame', sa.Integer(), nullable=True),
    sa.Column('endFrame', sa.Integer(), nullable=True),
    sa.Column('taskId', sa.Integer(), nullable=True),
    sa.Column('jobFile', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['taskId'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunk')
    op.drop_table('task')
    # ### end Alembic commands ###
