"""empty message

Revision ID: 33bde79cd629
Revises: b81d929e47bc
Create Date: 2016-12-05 12:19:34.945229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33bde79cd629'
down_revision = 'b81d929e47bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('jobFileType', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunk', 'jobFileType')
    # ### end Alembic commands ###
