"""empty message

Revision ID: 8f2449a5abe0
Revises: 2ce8ab035ef6
Create Date: 2016-12-04 01:14:51.417372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f2449a5abe0'
down_revision = '2ce8ab035ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunk', 'available')
    # ### end Alembic commands ###
