"""empty message

Revision ID: b81d929e47bc
Revises: 75525bf5d3e5
Create Date: 2016-12-05 10:23:48.322995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b81d929e47bc'
down_revision = '75525bf5d3e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunk', 'done')
    # ### end Alembic commands ###
