"""empty message

Revision ID: d4fdd86f11fe
Revises: 
Create Date: 2016-12-19 23:01:32.520927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4fdd86f11fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('startFrame', sa.Integer(), nullable=True),
    sa.Column('endFrame', sa.Integer(), nullable=True),
    sa.Column('num_chunks', sa.Integer(), nullable=True),
    sa.Column('filePath', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('lastOnline', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startFrame', sa.Integer(), nullable=True),
    sa.Column('endFrame', sa.Integer(), nullable=True),
    sa.Column('jobId', sa.Integer(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('worker', sa.Integer(), nullable=True),
    sa.Column('jobFile', sa.String(length=128), nullable=True),
    sa.Column('jobFileType', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['jobId'], ['job.id'], ),
    sa.ForeignKeyConstraint(['worker'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunk')
    op.drop_table('worker')
    op.drop_table('job')
    # ### end Alembic commands ###
